# Generated by Django 3.2.9 on 2022-01-20 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='boards_pics/')),
                ('total_flyers', models.CharField(blank=True, max_length=100, null=True)),
                ('total_posted', models.CharField(blank=True, max_length=100, null=True)),
                ('space_available', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Low Traffic'), (2, 'Medium Traffic'), (3, 'High Traffic')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='office_pics/')),
                ('updated_by', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='flyer_pics/')),
                ('removed', models.BooleanField(default=False)),
                ('flyer_creator', models.IntegerField(blank=True, choices=[(1, 'Student Affairs'), (2, 'External Office')], null=True)),
                ('flyer_edited', models.IntegerField(blank=True, choices=[(1, 'Student Affairs'), (2, 'External Office')], null=True)),
                ('date_posted', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('board', models.ManyToManyField(to='boardapp.Board')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapp.office')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
