# Generated by Django 3.2.9 on 2021-11-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='boards_pics/')),
                ('total_flyers', models.CharField(max_length=100)),
                ('total_posted', models.CharField(max_length=100)),
                ('space_available', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Low Traffic'), (2, 'Medium Traffic'), (3, 'High Traffic')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='office_pics/')),
                ('flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapp.board')),
            ],
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='flyer_pics/')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapp.board')),
            ],
        ),
    ]
