# Generated by Django 3.2.9 on 2021-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='space_available',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='total_flyers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='total_posted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
