# Generated by Django 3.2.9 on 2021-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flyer',
            name='board',
        ),
        migrations.AddField(
            model_name='flyer',
            name='board',
            field=models.ManyToManyField(to='boardapp.Board'),
        ),
    ]
