# Generated by Django 3.2.9 on 2021-11-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20211119_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='flyer',
        ),
        migrations.AddField(
            model_name='flyer',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boardapp.office'),
            preserve_default=False,
        ),
    ]
