# Generated by Django 3.2.9 on 2021-11-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20211120_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
