# Generated by Django 3.2.9 on 2021-11-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_alter_flyer_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
