# Generated by Django 3.2.9 on 2022-01-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0009_flyer_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='flyer_creator',
            field=models.IntegerField(blank=True, choices=[(1, 'Student Affairs'), (2, 'External Office')], null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='flyer_edited',
            field=models.IntegerField(blank=True, choices=[(1, 'Student Affairs'), (2, 'External Office')], null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
